### ISSUE TITLE
[npm install] Error: ENOENT: no such file or directory, open '.env'

### ISSUE THREAD

**Issue by AaronChern** [anmonite/wows-stats-plus#20]
Hi @anmonite  

I install the latest Node.js and re-install this app.
The following error message occurs. 
Will this affect the function of this app?

C:\Games\wows-stats-plus-master>start "" http://localhost:8080

C:\Games\wows-stats-plus-master>npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://git
hub.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> wows-stats-plus@1.2.1 postinstall C:\Games\wows-stats-plus-master
> node install.js

Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.config (C:\Games\wows-stats-plus-master\node_modules\dotenv\lib\ma
in.js:30:37)
    at Object.<anonymous> (C:\Games\wows-stats-plus-master\install.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '.env'
}
wows-stats installer is running on port: 8080

**Comment by AaronChern** [comment]
I drag a replay file to view_chrome.bat in file explorer.
The app runs, but no data read.
Is there any possible settings I forget to set?  (firewall, API agreement, browser setting?)

Replay Setting:  Enable versioned replays folder.

=====


C:\Users\user\Downloads>start "" chrome --new-window --app=http://localhost:8080


C:\Users\user\Downloads>set NODE_CAPTURE=true

C:\Users\user\Downloads>set NODE_ENV=production

C:\Users\user\Downloads>C:

C:\Users\user\Downloads>cd "\Games\wows-stats-plus-master\"

C:\Games\wows-stats-plus-master>node index.js 6973_1596090804_20200730_080954_PB
SD106-Icarus_17_NA_fault_line
wows-stats-plus is running on port: 8080
latest season number of rank battle = 29
Got expected json file for PR.
Download & Overwrite completed as './static/js/expected.json'.
Success copy to 'expected_stable.json'.


![not_load](https://user-images.githubusercontent.com/1495279/88896476-7b062780-d27c-11ea-82a3-ac614b86605f.png)

**Comment by anmonite** [comment]
Hi, AaronChern.
The second post have to be reported as a new issue.

**Comment by AaronChern** [comment]
> Hi, AaronChern.
> The second post have to be reported as a new issue.
Hi @anmonite 

I move the second post here.
https://github.com/anmonite/wows-stats-plus/issues/21

**Comment by AaronChern** [comment]
![debug_2](https://user-images.githubusercontent.com/1495279/93018643-d3627000-f603-11ea-95bc-07b7866330a3.png)

**Comment by anmonite** [comment]
Support for the `request` module ended with version 2.88.1, released on August 11, 2018, as the final version in the official repository.
The `request` v2.88.2 version you reported no longer exists because its release was withdrawn.

https://github.com/request/request/tags

Currently, as far as making calls to the WarGaming API is concerned, even though support for the module has ended, request v2.88.1 works fine, so reverting to this version should resolve the issue.
