### ISSUE TITLE
Error: listen EACCES: permission denied 127.0.0.1:8080

### ISSUE THREAD

**Issue by asuna** [anmonite/wows-stats-plus#35]
After execute install.bat some error messages appeared (even run as admin), node version is: v16.13.1

````
C:\Users\user\wows-stats-plus>install.bat
C:\Users\user\wows-stats-plus>start "" http://localhost:8080
C:\Users\user\wows-stats-plus>npm install
C:\Users\user\wows-stats-plus>npm install
> wows-stats-plus@1.3.6 postinstall
> node install.js
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Object.config (C:\Users\user\wows-stats-plus\node_modules\dotenv\lib\main.js:30:37)
    at Object.<anonymous> (C:\Users\user\wows-stats-plus\install.js:1:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
wows-stats installer is running on port: 8080
node:events:368
      throw er; // Unhandled 'error' event
      ^
Error: listen EACCES: permission denied 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (node:net:1317:21)
    at listenInCluster (node:net:1382:12)
    at doListen (node:net:1520:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1361:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
npm ERR! code 1
npm ERR! path C:\Users\user\wows-stats-plus
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-12-17T13_45_47_510Z-debug-0.log
````

Details in debug log file:
> 0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@8.3.0
2 info using node@v16.13.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\user\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\user\wows-stats-plus\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\user\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\user\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 17ms
19 timing npm:load:configload Completed in 18ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 5ms
22 timing npm:load:display Completed in 7ms
23 verbose logfile C:\Users\user\AppData\Local\npm-cache\_logs\2021-12-17T13_45_47_510Z-debug-0.log
24 timing npm:load:logFile Completed in 11ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 39ms
28 timing arborist:ctor Completed in 1ms
29 silly logfile start cleaning logs, removing 1 files
30 timing idealTree:init Completed in 140ms
31 timing idealTree:userRequests Completed in 0ms
32 silly idealTree buildDeps
33 timing idealTree:#root Completed in 1ms
34 timing idealTree:buildDeps Completed in 3ms
35 timing idealTree:fixDepFlags Completed in 1ms
36 timing idealTree Completed in 150ms
37 timing arborist:ctor Completed in 0ms
38 timing reify:loadTrees Completed in 218ms
39 timing reify:diffTrees Completed in 9ms
40 silly reify moves {}
41 timing reify:retireShallow Completed in 0ms
42 timing reify:createSparse Completed in 0ms
43 timing reify:loadBundles Completed in 0ms
44 silly audit bulk request {
44 silly audit   accepts: [ '1.3.7' ],
44 silly audit   ajv: [ '6.12.6' ],
44 silly audit   'array-flatten': [ '1.1.1' ],
44 silly audit   asn1: [ '0.2.6' ],
44 silly audit   'assert-plus': [ '1.0.0' ],
44 silly audit   asynckit: [ '0.4.0' ],
44 silly audit   'aws-sign2': [ '0.7.0' ],
44 silly audit   aws4: [ '1.11.0' ],
44 silly audit   'bcrypt-pbkdf': [ '1.0.2' ],
44 silly audit   'body-parser': [ '1.19.1' ],
44 silly audit   bytes: [ '3.1.1' ],
44 silly audit   caseless: [ '0.12.0' ],
44 silly audit   'combined-stream': [ '1.0.8' ],
44 silly audit   'content-disposition': [ '0.5.4' ],
44 silly audit   'content-type': [ '1.0.4' ],
44 silly audit   cookie: [ '0.4.1' ],
44 silly audit   'cookie-signature': [ '1.0.6' ],
44 silly audit   'core-util-is': [ '1.0.2' ],
44 silly audit   dashdash: [ '1.14.1' ],
44 silly audit   debug: [ '2.6.9' ],
44 silly audit   'delayed-stream': [ '1.0.0' ],
44 silly audit   depd: [ '1.1.2' ],
44 silly audit   destroy: [ '1.0.4' ],
44 silly audit   dotenv: [ '1.2.0' ],
44 silly audit   'ecc-jsbn': [ '0.1.2' ],
44 silly audit   'ee-first': [ '1.1.1' ],
44 silly audit   encodeurl: [ '1.0.2' ],
44 silly audit   'escape-html': [ '1.0.3' ],
44 silly audit   etag: [ '1.8.1' ],
44 silly audit   express: [ '4.17.2' ],
44 silly audit   extend: [ '3.0.2' ],
44 silly audit   extsprintf: [ '1.3.0' ],
44 silly audit   'fast-deep-equal': [ '3.1.3' ],
44 silly audit   'fast-json-stable-stringify': [ '2.1.0' ],
44 silly audit   finalhandler: [ '1.1.2' ],
44 silly audit   'forever-agent': [ '0.6.1' ],
44 silly audit   'form-data': [ '2.3.3' ],
44 silly audit   forwarded: [ '0.2.0' ],
44 silly audit   fresh: [ '0.5.2' ],
44 silly audit   getpass: [ '0.1.7' ],
44 silly audit   'graceful-fs': [ '4.2.8' ],
44 silly audit   'har-schema': [ '2.0.0' ],
44 silly audit   'har-validator': [ '5.1.5' ],
44 silly audit   'http-errors': [ '1.8.1' ],
44 silly audit   'http-signature': [ '1.2.0' ],
44 silly audit   'iconv-lite': [ '0.4.24' ],
44 silly audit   inherits: [ '2.0.4' ],
44 silly audit   'ipaddr.js': [ '1.9.1' ],
44 silly audit   'is-typedarray': [ '1.0.0' ],
44 silly audit   isstream: [ '0.1.2' ],
44 silly audit   jsbn: [ '0.1.1' ],
44 silly audit   'json-schema': [ '0.4.0' ],
44 silly audit   'json-schema-traverse': [ '0.4.1' ],
44 silly audit   'json-stringify-safe': [ '5.0.1' ],
44 silly audit   jsonfile: [ '2.4.0' ],
44 silly audit   jsprim: [ '1.4.2' ],
44 silly audit   'media-typer': [ '0.3.0' ],
44 silly audit   'merge-descriptors': [ '1.0.1' ],
44 silly audit   methods: [ '1.1.2' ],
44 silly audit   mime: [ '1.6.0' ],
44 silly audit   'mime-db': [ '1.51.0' ],
44 silly audit   'mime-types': [ '2.1.34' ],
44 silly audit   ms: [ '2.0.0', '2.1.3' ],
44 silly audit   negotiator: [ '0.6.2' ],
44 silly audit   'oauth-sign': [ '0.9.0' ],
44 silly audit   'on-finished': [ '2.3.0' ],
44 silly audit   parseurl: [ '1.3.3' ],
44 silly audit   'path-to-regexp': [ '0.1.7' ],
44 silly audit   'performance-now': [ '2.1.0' ],
44 silly audit   'proxy-addr': [ '2.0.7' ],
44 silly audit   psl: [ '1.8.0' ],
44 silly audit   punycode: [ '2.1.1' ],
44 silly audit   qs: [ '6.9.6', '6.5.2' ],
44 silly audit   'range-parser': [ '1.2.1' ],
44 silly audit   'raw-body': [ '2.4.2' ],
44 silly audit   request: [ '2.88.2' ],
44 silly audit   'safe-buffer': [ '5.2.1' ],
44 silly audit   'safer-buffer': [ '2.1.2' ],
44 silly audit   send: [ '0.17.2' ],
44 silly audit   'serve-static': [ '1.14.2' ],
44 silly audit   setprototypeof: [ '1.2.0' ],
44 silly audit   sshpk: [ '1.16.1' ],
44 silly audit   statuses: [ '1.5.0' ],
44 silly audit   toidentifier: [ '1.0.1' ],
44 silly audit   'tough-cookie': [ '2.5.0' ],
44 silly audit   'tunnel-agent': [ '0.6.0' ],
44 silly audit   tweetnacl: [ '0.14.5' ],
44 silly audit   'type-is': [ '1.6.18' ],
44 silly audit   unpipe: [ '1.0.0' ],
44 silly audit   'uri-js': [ '4.4.1' ],
44 silly audit   'utils-merge': [ '1.0.1' ],
44 silly audit   uuid: [ '3.4.0' ],
44 silly audit   vary: [ '1.1.2' ],
44 silly audit   verror: [ '1.10.0' ]
44 silly audit }
45 timing reify:unpack Completed in 5ms
46 timing reify:unretire Completed in 0ms
47 timing build:queue Completed in 1ms
48 timing build:deps Completed in 1ms
49 timing build Completed in 1ms
50 timing reify:build Completed in 2ms
51 timing reify:trash Completed in 0ms
52 timing reify:save Completed in 26ms
53 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1185ms
54 timing auditReport:getReport Completed in 1191ms
55 silly audit report {}
56 timing auditReport:init Completed in 0ms
57 timing reify:audit Completed in 1193ms
58 timing reify Completed in 1442ms
59 timing command:install Completed in 2062ms
60 verbose stack Error: command failed
60 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
60 verbose stack     at ChildProcess.emit (node:events:390:28)
60 verbose stack     at maybeClose (node:internal/child_process:1064:16)
60 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
61 verbose pkgid wows-stats-plus@1.3.6
62 verbose cwd C:\Users\user\wows-stats-plus
63 verbose Windows_NT 10.0.19044
64 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
65 verbose node v16.13.1
66 verbose npm  v8.3.0
67 error code 1
68 error path C:\Users\user\wows-stats-plus
69 error command failed
70 error command C:\Windows\system32\cmd.exe /d /s /c node install.js
71 verbose exit 1
72 timing npm Completed in 2745ms
73 verbose code 1
74 error A complete log of this run can be found in:
74 error     C:\Users\user\AppData\Local\npm-cache\_logs\2021-12-17T13_45_47_510Z-debug-0.log

**Comment by anmonite** [comment]
Hi asuna,

It seems that this issue is a node.js module related problem. Not on my app.
So that you should re-install latest node.js and execute install.bat again.

If you already try that, I don't know how to resolve this issue.

Please report your 2nd try.

**Comment by anmonite** [comment]
I could not reproduce that behavior and di not received 2nd report by the reporter.
